import streamlit as st
import pandas as pd
import joblib
import os

current_dir = os.path.dirname(os.path.abspath(__file__))
model_path = os.path.join(current_dir, 'modelo_diabetes.pkl')


try:
    modelo = joblib.load(model_path)
except FileNotFoundError:
    raise Exception(f"Arquivo {model_path} não encontrado! Verifique o repositório no GitHub.")

st.title('Diabetes Prediction')
st.write('**⚠️ Disclaimer**: This is an **introductory student project** for educational purposes only. The predictions and results generated by this model **should not be taken seriously** for real-world medical decisions. Always consult a healthcare professional for diabetes diagnosis and treatment.')
st.header('Insere os teus dados para prever se tens diabetes')
pregnancies = st.number_input('Número de gravidezes', 0, 20)
glucose = st.number_input('Concentração de glicose (mg/dL)', 0, 200)
blood_pressure = st.number_input('Pressão arterial (mmHg)', 0, 150)
skin_thickness = st.number_input('Espessura da pele (mm)', 0, 50)
insulin = st.number_input('Insulina (mu U/ml)', 0, 900)
bmi = st.number_input('Índice de massa corporal (kg/m^2)', 0.0, 60.0)
dpf = st.number_input("Histórico familiar de diabetes (0-2)", 0.0, 2.0)
age = st.number_input("Idade", 0, 120)


if st.button("Prever Diabetes"):
    dados = pd.DataFrame([[
        pregnancies,
        glucose,
        blood_pressure,
        skin_thickness,
        insulin,
        bmi,
        dpf,
        age
    ]], columns=['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age'])
    
    predicao = modelo.predict(dados)
    
    if predicao[0] == 1:
        st.error('Risco de diabetes detectado')
    else:
        st.success('Sem risco de diabetes')
